疲れている。

---

Kotlin の coroutine での例外の扱いについて。 `CoroutineExceptionHandler` https://kotlinlang.org/docs/reference/coroutines/exception-handling.html とか言うのを `launch(handler)` な感じで設定すると `CancellationException` の wrap がされていなくて嬉しい。  `launch` の引数だけど `CoroutineContext` になっていた。 `CoroutineExceptionHandler` はそれを実装しているっぽい。うーん。何を書いているのか。よく分かってない。雰囲気で使っている。
